# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlTab.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ControlTab(object):
    def setupUi(self, ControlTab):
        ControlTab.setObjectName("ControlTab")
        ControlTab.resize(724, 441)
        ControlTab.setToolTip("")
        self.layoutWidget = QtWidgets.QWidget(ControlTab)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 371, 302))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spnSAngle = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnSAngle.setObjectName("spnSAngle")
        self.gridLayout.addWidget(self.spnSAngle, 3, 1, 1, 1)
        self.spnVAngle = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnVAngle.setObjectName("spnVAngle")
        self.gridLayout.addWidget(self.spnVAngle, 2, 1, 1, 1)
        self.btnExecute = QtWidgets.QPushButton(self.layoutWidget)
        self.btnExecute.setObjectName("btnExecute")
        self.gridLayout.addWidget(self.btnExecute, 9, 3, 1, 1)
        self.spnConditionValue = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnConditionValue.setObjectName("spnConditionValue")
        self.gridLayout.addWidget(self.spnConditionValue, 9, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.spnHAngle = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnHAngle.setObjectName("spnHAngle")
        self.gridLayout.addWidget(self.spnHAngle, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.spnEAngle = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnEAngle.setObjectName("spnEAngle")
        self.gridLayout.addWidget(self.spnEAngle, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.spnIAngle = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnIAngle.setObjectName("spnIAngle")
        self.gridLayout.addWidget(self.spnIAngle, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.cmbCollectMode = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbCollectMode.setObjectName("cmbCollectMode")
        self.cmbCollectMode.addItem("")
        self.cmbCollectMode.addItem("")
        self.cmbCollectMode.addItem("")
        self.cmbCollectMode.addItem("")
        self.gridLayout.addWidget(self.cmbCollectMode, 0, 0, 1, 2)
        self.cmbStopType = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbStopType.setObjectName("cmbStopType")
        self.cmbStopType.addItem("")
        self.cmbStopType.addItem("")
        self.gridLayout.addWidget(self.cmbStopType, 9, 1, 1, 1)
        self.spnITime = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnITime.setObjectName("spnITime")
        self.gridLayout.addWidget(self.spnITime, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lwdActionList = QtWidgets.QListWidget(self.layoutWidget)
        self.lwdActionList.setObjectName("lwdActionList")
        self.gridLayout.addWidget(self.lwdActionList, 0, 3, 5, 1)
        self.btnClear = QtWidgets.QPushButton(self.layoutWidget)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 8, 3, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(self.layoutWidget)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 6, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.layoutWidget1 = QtWidgets.QWidget(ControlTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 360, 371, 53))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spnChannelNumber = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spnChannelNumber.setMaximum(3)
        self.spnChannelNumber.setObjectName("spnChannelNumber")
        self.gridLayout_2.addWidget(self.spnChannelNumber, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 3, 1, 1)
        self.spnSamplingDepth = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spnSamplingDepth.setMinimum(1)
        self.spnSamplingDepth.setMaximum(16000)
        self.spnSamplingDepth.setObjectName("spnSamplingDepth")
        self.gridLayout_2.addWidget(self.spnSamplingDepth, 1, 1, 1, 1)
        self.spnAccumulativeFrequency = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spnAccumulativeFrequency.setMinimum(1)
        self.spnAccumulativeFrequency.setMaximum(65536)
        self.spnAccumulativeFrequency.setObjectName("spnAccumulativeFrequency")
        self.gridLayout_2.addWidget(self.spnAccumulativeFrequency, 1, 2, 1, 1)
        self.spnPulseWidth = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spnPulseWidth.setMinimum(1)
        self.spnPulseWidth.setMaximum(200)
        self.spnPulseWidth.setObjectName("spnPulseWidth")
        self.gridLayout_2.addWidget(self.spnPulseWidth, 1, 3, 1, 1)
        self.btnConfirm = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnConfirm.setObjectName("btnConfirm")
        self.gridLayout_2.addWidget(self.btnConfirm, 1, 4, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(ControlTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(420, 30, 254, 164))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 2)
        self.lblCurrentVerticalAngle = QtWidgets.QLabel(self.layoutWidget2)
        self.lblCurrentVerticalAngle.setObjectName("lblCurrentVerticalAngle")
        self.gridLayout_3.addWidget(self.lblCurrentVerticalAngle, 1, 2, 1, 2)
        self.btnDown = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnDown.setObjectName("btnDown")
        self.gridLayout_3.addWidget(self.btnDown, 4, 1, 1, 2)
        self.lblCurrentHorizontalAngle = QtWidgets.QLabel(self.layoutWidget2)
        self.lblCurrentHorizontalAngle.setObjectName("lblCurrentHorizontalAngle")
        self.gridLayout_3.addWidget(self.lblCurrentHorizontalAngle, 0, 2, 1, 2)
        self.btnUp = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnUp.setObjectName("btnUp")
        self.gridLayout_3.addWidget(self.btnUp, 2, 1, 1, 2)
        self.btnLeft = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnLeft.setObjectName("btnLeft")
        self.gridLayout_3.addWidget(self.btnLeft, 3, 0, 1, 1)
        self.btnRight = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnRight.setObjectName("btnRight")
        self.gridLayout_3.addWidget(self.btnRight, 3, 3, 1, 1)

        self.retranslateUi(ControlTab)
        QtCore.QMetaObject.connectSlotsByName(ControlTab)

    def retranslateUi(self, ControlTab):
        _translate = QtCore.QCoreApplication.translate
        ControlTab.setWindowTitle(_translate("ControlTab", "Form"))
        self.btnExecute.setStatusTip(_translate("ControlTab", "执行采集"))
        self.btnExecute.setText(_translate("ControlTab", "执行"))
        self.label_7.setText(_translate("ControlTab", "停止条件"))
        self.label_1.setText(_translate("ControlTab", "初始水平角度"))
        self.label_2.setText(_translate("ControlTab", "初始垂直角度"))
        self.label_3.setText(_translate("ControlTab", "开始角度"))
        self.label_5.setText(_translate("ControlTab", "间隔角度"))
        self.label_6.setText(_translate("ControlTab", "间隔时间"))
        self.cmbCollectMode.setItemText(0, _translate("ControlTab", "fixed_point"))
        self.cmbCollectMode.setItemText(1, _translate("ControlTab", "horizontal"))
        self.cmbCollectMode.setItemText(2, _translate("ControlTab", "vertical"))
        self.cmbCollectMode.setItemText(3, _translate("ControlTab", "driving"))
        self.cmbStopType.setItemText(0, _translate("ControlTab", "次数"))
        self.cmbStopType.setItemText(1, _translate("ControlTab", "时间(s)"))
        self.label_4.setText(_translate("ControlTab", "结束角度"))
        self.btnClear.setStatusTip(_translate("ControlTab", "增加一条动作"))
        self.btnClear.setText(_translate("ControlTab", "清除"))
        self.btnAdd.setStatusTip(_translate("ControlTab", "增加一条动作"))
        self.btnAdd.setText(_translate("ControlTab", "Add"))
        self.label_8.setText(_translate("ControlTab", "通道号"))
        self.label_10.setText(_translate("ControlTab", "累加次数"))
        self.label_9.setText(_translate("ControlTab", "采样深度"))
        self.label_11.setText(_translate("ControlTab", "脉冲宽度"))
        self.btnConfirm.setStatusTip(_translate("ControlTab", "设置采集卡参数"))
        self.btnConfirm.setText(_translate("ControlTab", "Ok"))
        self.label_13.setText(_translate("ControlTab", "垂直"))
        self.label_12.setText(_translate("ControlTab", "水平"))
        self.lblCurrentVerticalAngle.setText(_translate("ControlTab", "0"))
        self.btnDown.setText(_translate("ControlTab", "Down"))
        self.lblCurrentHorizontalAngle.setText(_translate("ControlTab", "0"))
        self.btnUp.setText(_translate("ControlTab", "Up"))
        self.btnLeft.setText(_translate("ControlTab", "Left"))
        self.btnRight.setText(_translate("ControlTab", "Right"))

