# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlTab.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ControlTab(object):
    def setupUi(self, ControlTab):
        ControlTab.setObjectName("ControlTab")
        ControlTab.resize(724, 441)
        ControlTab.setToolTip("")
        self.widget = QtWidgets.QWidget(ControlTab)
        self.widget.setGeometry(QtCore.QRect(30, 30, 275, 291))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_12 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout.addWidget(self.spinBox_12, 7, 2, 1, 1)
        self.cmbCollectMode_4 = QtWidgets.QComboBox(self.widget)
        self.cmbCollectMode_4.setObjectName("cmbCollectMode_4")
        self.cmbCollectMode_4.addItem("")
        self.cmbCollectMode_4.addItem("")
        self.gridLayout.addWidget(self.cmbCollectMode_4, 7, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.btnExecute = QtWidgets.QPushButton(self.widget)
        self.btnExecute.setObjectName("btnExecute")
        self.gridLayout.addWidget(self.btnExecute, 8, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.spnHAngle = QtWidgets.QSpinBox(self.widget)
        self.spnHAngle.setObjectName("spnHAngle")
        self.gridLayout.addWidget(self.spnHAngle, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.spnVAngle = QtWidgets.QSpinBox(self.widget)
        self.spnVAngle.setObjectName("spnVAngle")
        self.gridLayout.addWidget(self.spnVAngle, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.spnSAngle = QtWidgets.QSpinBox(self.widget)
        self.spnSAngle.setObjectName("spnSAngle")
        self.gridLayout.addWidget(self.spnSAngle, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.spnEAngle = QtWidgets.QSpinBox(self.widget)
        self.spnEAngle.setObjectName("spnEAngle")
        self.gridLayout.addWidget(self.spnEAngle, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.spnIAngle = QtWidgets.QSpinBox(self.widget)
        self.spnIAngle.setObjectName("spnIAngle")
        self.gridLayout.addWidget(self.spnIAngle, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout.addWidget(self.spinBox_9, 6, 1, 1, 1)
        self.cmbCollectMode = QtWidgets.QComboBox(self.widget)
        self.cmbCollectMode.setObjectName("cmbCollectMode")
        self.cmbCollectMode.addItem("")
        self.cmbCollectMode.addItem("")
        self.cmbCollectMode.addItem("")
        self.cmbCollectMode.addItem("")
        self.cmbCollectMode.addItem("")
        self.gridLayout.addWidget(self.cmbCollectMode, 0, 0, 1, 2)
        self.widget1 = QtWidgets.QWidget(ControlTab)
        self.widget1.setGeometry(QtCore.QRect(30, 360, 381, 53))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBox = QtWidgets.QSpinBox(self.widget1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_2.addWidget(self.spinBox_3, 1, 2, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_2.addWidget(self.spinBox_4, 1, 3, 1, 1)
        self.btnDown_2 = QtWidgets.QPushButton(self.widget1)
        self.btnDown_2.setObjectName("btnDown_2")
        self.gridLayout_2.addWidget(self.btnDown_2, 1, 4, 1, 1)
        self.widget2 = QtWidgets.QWidget(ControlTab)
        self.widget2.setGeometry(QtCore.QRect(420, 30, 254, 164))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_1 = QtWidgets.QLabel(self.widget2)
        self.label_1.setObjectName("label_1")
        self.gridLayout_3.addWidget(self.label_1, 0, 0, 1, 2)
        self.lblCurrentVerticalAngle = QtWidgets.QLabel(self.widget2)
        self.lblCurrentVerticalAngle.setObjectName("lblCurrentVerticalAngle")
        self.gridLayout_3.addWidget(self.lblCurrentVerticalAngle, 1, 2, 1, 2)
        self.btnDown = QtWidgets.QPushButton(self.widget2)
        self.btnDown.setObjectName("btnDown")
        self.gridLayout_3.addWidget(self.btnDown, 4, 1, 1, 2)
        self.lblCurrentHorizontalAngle = QtWidgets.QLabel(self.widget2)
        self.lblCurrentHorizontalAngle.setObjectName("lblCurrentHorizontalAngle")
        self.gridLayout_3.addWidget(self.lblCurrentHorizontalAngle, 0, 2, 1, 2)
        self.btnUp = QtWidgets.QPushButton(self.widget2)
        self.btnUp.setObjectName("btnUp")
        self.gridLayout_3.addWidget(self.btnUp, 2, 1, 1, 2)
        self.btnLeft = QtWidgets.QPushButton(self.widget2)
        self.btnLeft.setObjectName("btnLeft")
        self.gridLayout_3.addWidget(self.btnLeft, 3, 0, 1, 1)
        self.btnRight = QtWidgets.QPushButton(self.widget2)
        self.btnRight.setObjectName("btnRight")
        self.gridLayout_3.addWidget(self.btnRight, 3, 3, 1, 1)

        self.retranslateUi(ControlTab)
        QtCore.QMetaObject.connectSlotsByName(ControlTab)

    def retranslateUi(self, ControlTab):
        _translate = QtCore.QCoreApplication.translate
        ControlTab.setWindowTitle(_translate("ControlTab", "Form"))
        self.cmbCollectMode_4.setItemText(0, _translate("ControlTab", "counts"))
        self.cmbCollectMode_4.setItemText(1, _translate("ControlTab", "stop_time"))
        self.label_13.setText(_translate("ControlTab", "停止条件"))
        self.btnExecute.setStatusTip(_translate("ControlTab", "执行动作"))
        self.btnExecute.setText(_translate("ControlTab", "执行"))
        self.label_7.setText(_translate("ControlTab", "初始水平角度"))
        self.label_8.setText(_translate("ControlTab", "初始垂直角度"))
        self.label_9.setText(_translate("ControlTab", "开始角度"))
        self.label_10.setText(_translate("ControlTab", "结束角度"))
        self.label_11.setText(_translate("ControlTab", "间隔角度"))
        self.label_12.setText(_translate("ControlTab", "次数"))
        self.cmbCollectMode.setItemText(0, _translate("ControlTab", "fixed_point"))
        self.cmbCollectMode.setItemText(1, _translate("ControlTab", "horizontal"))
        self.cmbCollectMode.setItemText(2, _translate("ControlTab", "vertical"))
        self.cmbCollectMode.setItemText(3, _translate("ControlTab", "driving"))
        self.cmbCollectMode.setItemText(4, _translate("ControlTab", "custom"))
        self.label_3.setText(_translate("ControlTab", "水平"))
        self.label_5.setText(_translate("ControlTab", "水平"))
        self.label_4.setText(_translate("ControlTab", "垂直"))
        self.label_6.setText(_translate("ControlTab", "垂直"))
        self.btnDown_2.setStatusTip(_translate("ControlTab", "设置采集卡参数"))
        self.btnDown_2.setText(_translate("ControlTab", "Ok"))
        self.label_2.setText(_translate("ControlTab", "垂直"))
        self.label_1.setText(_translate("ControlTab", "水平"))
        self.lblCurrentVerticalAngle.setText(_translate("ControlTab", "0"))
        self.btnDown.setText(_translate("ControlTab", "Down"))
        self.lblCurrentHorizontalAngle.setText(_translate("ControlTab", "0"))
        self.btnUp.setText(_translate("ControlTab", "Up"))
        self.btnLeft.setText(_translate("ControlTab", "Left"))
        self.btnRight.setText(_translate("ControlTab", "Right"))

